version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # or wherever your .csproj is
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
